############################################################################
name: Build java 
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
#Build for Windows
  build_win:
    runs-on: windows-latest
    steps:
      #CheckOut
      - uses: actions/checkout@v1
      - name: set up Java(JDK)
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          
      #Maven App Building
      - name: Maven Building
        run: mvn -B clean verify
      
      #Artifacts .jar
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact.jar
          path: download/artifacts.jar

        
#############################################################################
